version: '3'



services:
  go:
    build:
      context: .
    container_name: go-GraphQL
    tty: true
    volumes:
      - type: bind
      source: ./go
      target: ./go:/go/src
    ports:
      - 8080:8080
